### ISSUE TITLE
[BUG] Plugin not working as of 11/6/2025

### ISSUE THREAD

**Issue by Lord-Runes** [guillaume009/runelite-plugin-action-progress#123]
Not working at all. Hopefully the author updates the plugin to be compatible with the most recent update :)

**Comment by guillaume009** [comment]
Can you restart RuneLite? This was fixed last night in version 1.20

**Comment by Lord-Runes** [comment]
Well considering we all had to restart RuneLite after the update, and I just now did again.. There is still no overlay for
plank make spell or stringing bows. Those are the only 2 I have tested so far but it seems it is still broken.

**Comment by guillaume009** [comment]
PR towards RL hub for stringing and plank make created

https://github.com/runelite/plugin-hub/pull/9442
